### ISSUE TITLE
gpu configuation

### ISSUE THREAD

**Issue by wyfwyfwyfwyfwyfwyf** [KeiLongW/synthetic-battery-data#1]
Hello ,I have ran your code.I find that there are some problems in your code:
1.Your code needs to run on GPU,if runs on CPU,process will be killed.If my device has more than one GPU,how can I choose the GPU that I want to run this code on?(my device has 8 GPUs,GPU0-GPU7,I want to use GPU2 to run,what should I do?)
2.It seems that your code is not able to generate g_loss.json and d_loss.json,which will be used in result.ipynb.What can I do to solve these problems?

**Comment by KeiLongW** [comment]
1. you can set the env var of something like this: `CUDA_VISIBLE_DEVICES=2 python train_lstm_gan.py` to choose the GPU you need.
2. the loss json generates after each gan epoch, make sure you finish one epoch

**Comment by wyfwyfwyfwyfwyfwyf** [comment]
Thanks,I have solved all the problems above.
